<a href="https://colab.research.google.com/github/orangNLP/Modules_practice/blob/main/PyTorchpytorch_basic_tensor_handling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Run All Codes**

In [4]:
import torch
t = torch.FloatTensor([1,2,3,4,5,6])
t

tensor([1., 2., 3., 4., 5., 6.])

In [5]:
print(t.shape, #argument x
      t.size(),
      t.dim(), sep='\n')

torch.Size([6])
torch.Size([6])
1


In [6]:
twod = torch.FloatTensor([
    [1,2,3,4,5,6],
    [2,6,8,1,3,5],
    [7,5,3,2,1,4]
])

twod.shape

torch.Size([3, 6])

In [7]:
twod[0:3,1].reshape(3,1)

tensor([[2.],
        [6.],
        [5.]])

In [8]:
#broadcasting
m1 = torch.FloatTensor([[1,2]]) #1x2
m2 = torch.FloatTensor([[1],
                        [2]])   #2x1
m1 + m2

tensor([[2., 3.],
        [3., 4.]])

In [9]:
#matmul vs mul
#matrix multiple = matmul
torch.matmul(m1,m2) #[1x2] [2x1] = [1x1]
#== m1.matmul(m2)

tensor([[5.]])

In [10]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2

print(m1.mul(m2))

'''
[1, 2]      [1, 1]  =     [1, 2] 
[3, 4]      [2, 2]        [6, 8]
'''
print()

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])



In [11]:
t = torch.FloatTensor([[1, 2], [3, 4], [8, 7]])
print(t)
print(t.mean()) #모든 원소의 평균값

tensor([[1., 2.],
        [3., 4.],
        [8., 7.]])
tensor(4.1667)


In [12]:
print(t.mean(dim=1))

tensor([1.5000, 3.5000, 7.5000])


In [13]:
print(t.sum())
print(t.sum(dim=0))

tensor(25.)
tensor([12., 13.])


In [14]:
print(t.max())
print(t.max(dim=-1)) #max에 dim 인자를 주면 argmax도 함께 리턴됨

tensor(8.)
torch.return_types.max(
values=tensor([2., 4., 8.]),
indices=tensor([1, 1, 0]))


In [15]:
import numpy as np

t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [16]:
ft.shape

torch.Size([2, 2, 3])

In [17]:
ft.view(-1,3) #view == reshape in np. -1 입력시 자동 설정 

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [18]:
#squeeze -> 1인 차원 제거
ft = torch.FloatTensor([[[0], [1], [2]]])
print(ft)
print(ft.shape)

tensor([[[0.],
         [1.],
         [2.]]])
torch.Size([1, 3, 1])


In [19]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [20]:
ft.squeeze(2) #argument를 입력시 해당 차원이 1일 경우에만 제거

tensor([[0., 1., 2.]])

In [21]:
ft.unsqueeze(3) #1인 차원 추가

tensor([[[[0.]],

         [[1.]],

         [[2.]]]])

In [22]:
lt = torch.LongTensor([1, 2, 3, 4]) #int64
print(lt) 

tensor([1, 2, 3, 4])


In [40]:
print(lt.float())
print(torch.FloatTensor([1,255,256,258,322]).byte())

tensor([1., 2., 3., 4.])
tensor([  1, 255,   0,   2,  66], dtype=torch.uint8)


In [42]:
#concatenate -> 행렬 연결
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
torch.concatenate([x,y])

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [46]:
torch.cat((x,y), dim=1)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

In [47]:
#stack
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [62]:
import time
start_time = time.time()
print(torch.stack((x,y,z)))
end_time = time.time()
print(end_time-start_time)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
0.005827426910400391


In [51]:
torch.stack((x,y,z),dim=1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [61]:
import time
start_time = time.time()
print(torch.cat((x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)), dim=0))
end_time = time.time()
print(end_time-start_time)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
0.0067942142486572266


In [63]:
torch.cat((x.unsqueeze(1),y.unsqueeze(1),z.unsqueeze(1)), dim=1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [70]:
x = np.ones((5,4))
print(torch.ones_like(torch.FloatTensor(x)),
torch.zeros_like(torch.FloatTensor(x)),sep = '\n\n')

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [83]:
#덮어쓰기 연산 _
x= torch.FloatTensor([[1,2,3],[2,5,7]])
x.mul(3)
print(x)

tensor([[1., 2., 3.],
        [2., 5., 7.]])


In [86]:
x.mul_(3)
print(x)

tensor([[ 27.,  54.,  81.],
        [ 54., 135., 189.]])


In [90]:
torch.zeros((2,2,4), requires_grad = True)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]], requires_grad=True)