<a href="https://colab.research.google.com/github/orangNLP/Modules_practice/blob/main/pytorch/pytorch_Mini_Batch_%26_Data_Load.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
x_train = torch.FloatTensor([[73, 80, 75], #(5,3)
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]]) #(1,5)

In [ ]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [ ]:
dataset = TensorDataset(x_train, y_train)


In [ ]:
dataloader = DataLoader(dataset, batch_size = 2, shuffle = True)

In [ ]:
model = nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [ ]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):
  for batch_idx, samples in enumerate(dataloader):
    x_train, y_train = samples
    
    Hx = model(x_train)

    loss_function = F.mse_loss(Hx, y_train)

    optimizer.zero_grad()
    loss_function.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        loss_function.item()))

Epoch    0/20 Batch 1/3 Cost: 3232.834229
Epoch    0/20 Batch 2/3 Cost: 1359.798340
Epoch    0/20 Batch 3/3 Cost: 210.537720
Epoch    1/20 Batch 1/3 Cost: 143.914459
Epoch    1/20 Batch 2/3 Cost: 33.184315
Epoch    1/20 Batch 3/3 Cost: 5.824677
Epoch    2/20 Batch 1/3 Cost: 7.216097
Epoch    2/20 Batch 2/3 Cost: 0.135182
Epoch    2/20 Batch 3/3 Cost: 8.698431
Epoch    3/20 Batch 1/3 Cost: 0.686336
Epoch    3/20 Batch 2/3 Cost: 1.933737
Epoch    3/20 Batch 3/3 Cost: 6.069965
Epoch    4/20 Batch 1/3 Cost: 0.878145
Epoch    4/20 Batch 2/3 Cost: 3.461931
Epoch    4/20 Batch 3/3 Cost: 0.266956
Epoch    5/20 Batch 1/3 Cost: 0.717195
Epoch    5/20 Batch 2/3 Cost: 2.291249
Epoch    5/20 Batch 3/3 Cost: 3.560802
Epoch    6/20 Batch 1/3 Cost: 1.620100
Epoch    6/20 Batch 2/3 Cost: 2.623877
Epoch    6/20 Batch 3/3 Cost: 2.703279
Epoch    7/20 Batch 1/3 Cost: 0.040240
Epoch    7/20 Batch 2/3 Cost: 3.736011
Epoch    7/20 Batch 3/3 Cost: 2.306101
Epoch    8/20 Batch 1/3 Cost: 0.766087
Epoch    8/20 

In [ ]:
new_var = torch.FloatTensor([53,31,64])
pred_y = model(new_var)
print (pred_y)

tensor([104.2995], grad_fn=<AddBackward0>)


In [ ]:
  list(model.parameters())

[Parameter containing:
 tensor([[0.5132, 0.5512, 0.9317]], requires_grad=True), Parameter containing:
 tensor([0.3797], requires_grad=True)]