<a href="https://colab.research.google.com/github/orangNLP/Modules_practice/blob/main/pytorch/pytorch_nn_Modules.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Run All Codes**

In [165]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

##**Linear Regression**

In [166]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [167]:
x_train

tensor([[1.],
        [2.],
        [3.]])

In [168]:
W = torch.zeros(1, requires_grad =  True)
W

tensor([0.], requires_grad=True)

In [169]:
b = torch.zeros(1, requires_grad = True)
b

tensor([0.], requires_grad=True)

In [170]:
hypothesis = torch.matmul(x_train, W) + b
hypothesis

tensor([0., 0., 0.], grad_fn=<AddBackward0>)

In [171]:
cost = torch.mean((hypothesis - y_train)**2)
cost

tensor(18.6667, grad_fn=<MeanBackward0>)

In [172]:
optimizer = optim.SGD([W,b], lr = 0.01)

In [173]:
optimizer.zero_grad()
cost.backward() #미분
optimizer.step()

In [174]:
cost.backward

<bound method Tensor.backward of tensor(18.6667, grad_fn=<MeanBackward0>)>

In [175]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])
W = torch.zeros(1, requires_grad =  True)
b = torch.zeros(1, requires_grad = True)
epochs = 2000
for i in range(epochs+1):
  hypothesis = x_train.matmul(W) + b
  cost = torch.mean((hypothesis - y_train)**2)
  optimizer = optim.SGD([W,b], lr = 0.01)
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()
  print(W.grad)
  if i % 100 == 0:
    print('epochs:', i, f'W: {W[0]}, b: {b[0]}, cost: {cost}')

tensor([-16.])
epochs: 0 W: 0.1599999964237213, b: 0.07999999821186066, cost: 18.66666603088379
tensor([-14.1867])
tensor([-12.5746])
tensor([-11.1414])
tensor([-9.8673])
tensor([-8.7346])
tensor([-7.7277])
tensor([-6.8326])
tensor([-6.0368])
tensor([-5.3294])
tensor([-4.7006])
tensor([-4.1416])
tensor([-3.6447])
tensor([-3.2031])
tensor([-2.8105])
tensor([-2.4615])
tensor([-2.1514])
tensor([-1.8757])
tensor([-1.6307])
tensor([-1.4130])
tensor([-1.2195])
tensor([-1.0476])
tensor([-0.8948])
tensor([-0.7591])
tensor([-0.6385])
tensor([-0.5313])
tensor([-0.4362])
tensor([-0.3517])
tensor([-0.2766])
tensor([-0.2100])
tensor([-0.1508])
tensor([-0.0983])
tensor([-0.0517])
tensor([-0.0103])
tensor([0.0263])
tensor([0.0588])
tensor([0.0877])
tensor([0.1132])
tensor([0.1358])
tensor([0.1559])
tensor([0.1736])
tensor([0.1893])
tensor([0.2031])
tensor([0.2154])
tensor([0.2262])
tensor([0.2357])
tensor([0.2440])
tensor([0.2514])
tensor([0.2579])
tensor([0.2635])
tensor([0.2685])
tensor([0.2728])
t

##**Autograd**

In [176]:
w = torch.tensor(2.0, requires_grad=True)


In [177]:
y = w**2
z = 2*y + 5
z.backward()
print(w.grad)

tensor(8.)


In [178]:
x = torch.FloatTensor([[2,3,4,7,3], [3,2,6,2,1]])
w = torch.zeros((5,2), requires_grad = True)
b = torch.tensor(5.0, requires_grad = True)
z = torch.matmul(x, w) + b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)

True
False


##**nn.Module**

In [179]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [180]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [181]:
model = nn.Linear(1,1) #nn.Linear(input_dim. output_dim)
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.7351]], requires_grad=True), Parameter containing:
tensor([0.2376], requires_grad=True)]


In [182]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 

In [183]:
epochs = 2000
for i in range(epochs+1):
  Hx = model(x_train)
  cost =  F.mse_loss(Hx, y_train) #MeanSquaredError. Hx, y
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()
  if i % 100 == 0:
    print(f'epochs: {i}, W: {list(model.parameters())[0]}, b: {list(model.parameters())[1]}')

epochs: 0, W: Parameter containing:
tensor([[-0.4893]], requires_grad=True), b: Parameter containing:
tensor([0.3422], requires_grad=True)
epochs: 100, W: Parameter containing:
tensor([[1.5836]], requires_grad=True), b: Parameter containing:
tensor([0.9466], requires_grad=True)
epochs: 200, W: Parameter containing:
tensor([[1.6726]], requires_grad=True), b: Parameter containing:
tensor([0.7441], requires_grad=True)
epochs: 300, W: Parameter containing:
tensor([[1.7427]], requires_grad=True), b: Parameter containing:
tensor([0.5850], requires_grad=True)
epochs: 400, W: Parameter containing:
tensor([[1.7977]], requires_grad=True), b: Parameter containing:
tensor([0.4598], requires_grad=True)
epochs: 500, W: Parameter containing:
tensor([[1.8410]], requires_grad=True), b: Parameter containing:
tensor([0.3615], requires_grad=True)
epochs: 600, W: Parameter containing:
tensor([[1.8750]], requires_grad=True), b: Parameter containing:
tensor([0.2842], requires_grad=True)
epochs: 700, W: Param

In [184]:
type(list(model.parameters())[0])

torch.nn.parameter.Parameter

In [185]:
model(torch.FloatTensor([5]))

tensor([9.9883], grad_fn=<AddBackward0>)

In [186]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [187]:
Linear = nn.Linear(3,1)
list(Linear.parameters())

[Parameter containing:
 tensor([[ 0.3175,  0.0025, -0.1762]], requires_grad=True),
 Parameter containing:
 tensor([-0.4298], requires_grad=True)]

In [188]:
Linear_optimizer = optim.SGD(Linear.parameters(), lr = 1e-5)

In [189]:
epochs = 2000
for i in range(epochs+1):
  Hx = Linear(x_train)
  loss_function = F.mse_loss(Hx,y_train)
  Linear_optimizer.zero_grad()
  loss_function.backward()
  Linear_optimizer.step()
print(list(Linear.parameters()))

[Parameter containing:
tensor([[0.9802, 0.5784, 0.4596]], requires_grad=True), Parameter containing:
tensor([-0.4212], requires_grad=True)]


In [190]:
Linear(torch.FloatTensor([70, 60, 50]))

tensor([125.8732], grad_fn=<AddBackward0>)

In [191]:
class MultiLayerLinearRegression(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(3, 1) 
  
  def forward(self, x):
    return self.linear(x)
config = {'input_dim': 3, 'output_dim':1} 
Model = MultiLayerLinearRegression()
optimizer = optim.SGD(Model.parameters(), lr = 1e-5)
for i in range(epochs+1):
  Hx = Model(x_train)
  loss_function = F.mse_loss(Hx, y_train)
  optimizer.zero_grad()
  loss_function.backward()
  optimizer.step()

In [192]:
Model(torch.FloatTensor([1,21,50]))

tensor([32.7938], grad_fn=<AddBackward0>)